# Manager-Server
name: local_llm
host: 0.0.0.0
manager_port: 8080

# LLM-Prozess
command:
  - HSA_ENABLE_SDMA=0
  - /home/masterburns/llm-workspace/llama.cpp/build/bin/llama-server
  - -m
  - /home/masterburns/llm-workspace/qwn3.6/Qwen3.6-35B-A3B-MXFP4_MOE.gguf
  - -fa
  - "on"
  - -c
  - 192000
  - -ngl
  - 99
  - -ctk
  - q4_0
  - -ctv
  - q4_0
  - --port
  - 11434
  - --metrics
cwd: /home/masterburns/llm-workspace/llama.cpp
llm_port: 11434
health_url: http://127.0.0.1:11434/health
process_match: llama-server
